#!/bin/sh -ef

git clone https://github.com/kaitai-io/kaitai_struct_csharp_runtime /download/runtime/csharp
git clone https://github.com/kaitai-io/kaitai_struct_tests /download/tests

cd /download/tests
./run-csharp --project
dotnet restore spec/csharp/kaitai_struct_csharp_tests_netstd/kaitai_struct_csharp_tests_netstd.csproj

rm -rf /download
