#!/bin/sh -ef

# Ruby is necessary for CI infrastructure
apk update
apk add \
	ruby \
	ruby-json

# Modern Ruby doesn't ship by default with rexml-doc, so we check if this needs extra install
if ! echo 'require "rexml/document"' | ruby; then
	echo "no rexml/document detected, installing"
	apk add ruby-rexml
fi

# Cleanup apk cache
rm -rf /var/cache/apk/*
