#!/bin/sh -ef

if [ "$#" -lt 3 ]; then
    echo "Usage: $0 <software_name> <version_output> <grep_args>..." >&2
    exit 1
fi

software_name=$1
version_output=$2
shift 2

echo "${software_name} version:"
echo '---'
echo "$version_output"
echo '---'

if echo "$version_output" | grep -q "$@"; then
	echo "${software_name} version confirmed."
else
	echo "Wrong ${software_name} version detected!"
	exit 1
fi
