#!/bin/sh -ef

NODEJS_VERSION=$(node --version)

# Mocha dropped Node.js
#  - v4 since v6.0
#  - v8 since v8.0
#  - v10 since v9.0
#  - v12 since v10.0
# , so we'll be specifically using older versions
MOCHA_VERSION=
if echo "$NODEJS_VERSION" | grep '^v4\.'; then
	MOCHA_VERSION="@<6"
elif echo "$NODEJS_VERSION" | grep '^v8\.'; then
	MOCHA_VERSION="@<8"
elif echo "$NODEJS_VERSION" | grep '^v10\.'; then
	MOCHA_VERSION="@<9"
elif echo "$NODEJS_VERSION" | grep '^v12\.'; then
	MOCHA_VERSION="@<10"
fi

# Install JavaScript dependencies
npm install -g --loglevel verbose \
	"mocha$MOCHA_VERSION" \
	iconv-lite
