#!/bin/sh -ef

NODEJS_VERSION=$(node --version)

# Mocha dropped Node.js
#  - v4 since v6.0
#  - v8 since v8.0
#  - v10 since v9.0
#  - v12 since v10.0
# , so we'll be specifically using older versions
MOCHA_VERSION=
if echo "$NODEJS_VERSION" | grep '^v4'; then
	MOCHA_VERSION="@<6"
elif echo "$NODEJS_VERSION" | grep '^v8'; then
	MOCHA_VERSION="@<8"
elif echo "$NODEJS_VERSION" | grep '^v10'; then
	MOCHA_VERSION="@<9"
elif echo "$NODEJS_VERSION" | grep '^v12'; then
	MOCHA_VERSION="@<10"
fi

# Install JavaScript dependencies
npm install --loglevel verbose \
	"mocha$MOCHA_VERSION" \
	iconv-lite

# Ruby is necessary for CI infrastructure
apk update
apk add \
	ruby \
	ruby-json

# Modern Ruby doesn't ship by default with rexml-doc, so we check if this needs extra install
if ! echo 'require "rexml/document"' | ruby; then
	echo "no rexml/document detected, installing"
	apk add ruby-rexml
fi

# Cleanup apk cache
rm -rf /var/cache/apk/*
