#!/bin/sh -ef

apt-get install -y --no-install-recommends \
	git \
	unzip

# Install Kaitai Struct runtime
mkdir -p /download/runtime
git clone --depth 1 https://github.com/kaitai-io/kaitai_struct_php_runtime /download/runtime/php

# Install Composer
curl https://getcomposer.org/installer -o composer-setup.php
php ./composer-setup.php
mv composer.phar /usr/local/bin/composer

# Install runtime's dependencies: result is in /download/runtime/php/vendor.
cd /download/runtime/php
composer install
