#!/bin/sh -ef

# Generic ./build script that:
#
# 1. Prepares everything in 4img/ dir where Dockerfile is
# 2. Copies everything from target's `_common` to this 4img/ dir
# 3. Runs docker build with image name determined from path

# Detect location first
if [ ! -f ../../../LICENSE ]; then
	echo 'This script has to be ran as `./build` from `src/$TARGET/$IMPLEMENTATION-$OS-$ARCH` dir.'
	exit 1
fi

. ../../../common.sh

mkdir -p 4img
rsync -av ../../_common/ 4img

# Copy one level up common, if it exists
[ -d ../_common ] && rsync -av ../_common/ 4img

# If there's extra prebuild script, execute it before launching the build
if [ -f prebuild ]; then
	. ./prebuild
fi

"$DOCKER_BIN" $EXTRA_ARGS build -t "$IMG_NAME" --label io.kaitai.ci=true .
