#!/bin/sh -ef

# Generic ./build script that:
#
# 1. Prepares everything in 4img/ dir where Dockerfile is
# 2. Copies everything from target's `_common` to this 4img/ dir
# 3. Runs docker build with image name determined from path

# Detect location first
if [ ! -f ../../../LICENSE ]; then
	echo 'This script has to be ran as `./build` from `src/$TARGET/$IMPLEMENTATION-$OS-$ARCH` dir.'
	exit 1
fi

ALL=$(pwd | sed 's,^.*/src/,,')
TARGET=$(echo "$ALL" | cut -d/ -f1)
REST=$(echo "$ALL" | cut -d/ -f2)

IMG_NAME="kaitai-$TARGET-$REST"

mkdir -p 4img
rsync -av ../_common/ 4img
docker build -t "$IMG_NAME" --label kaitai.ci=true .
