#!/bin/sh -ef

# Generic ./run-it script that determines image name by where it's called from and launches interactive shell in a relevant image.

# Detect location first
if [ ! -f ../../../LICENSE ]; then
	echo 'This script has to be ran as `./run-it` from `src/$TARGET/$IMPLEMENTATION-$OS-$ARCH` dir.'
	exit 1
fi

. ../../../common.sh

"$DOCKER_BIN" $EXTRA_ARGS run --rm -it "$IMG_NAME" /bin/sh
